In [19]:
import numpy as np

# Define the vector space V and its dual V*
v = np.array([2, 3])  # Element of V
w = np.array([1, -1])  # Element of V*

# Define the tensor T
T = np.array([[2, 1],
              [-1, 3]])

# Perform the calculation T(v, w) using @ operator
result_at = w @ T @ v

# Perform the calculation T(v, w) using np.tensordot
result_tensordot = np.tensordot(np.tensordot(w, T, axes=1), v, axes=1)

print("V (column vector):", v)
print("V* (row vector):", w)
print("Tensor T:")
print(T)
print("Result of T(v, w) using @:", result_at)
print("Result of T(v, w) using tensordot:", result_tensordot)

# Additional example
v_prime = np.array([1, -1])
w_prime = np.array([2, 1])

result_prime_at = w_prime @ T @ v_prime
result_prime_tensordot = np.tensordot(
    np.tensordot(w_prime, T, axes=1), v_prime, axes=1)

print("\nAdditional example:")
print("V' (column vector):", v_prime)
print("V*' (row vector):", w_prime)
print("Result of T(v', w') using @:", result_prime_at)
print("Result of T(v', w') using tensordot:", result_prime_tensordot)

V (column vector): [2 3]
V* (row vector): [ 1 -1]
Tensor T:
[[ 2  1]
 [-1  3]]
Result of T(v, w) using @: 0
Result of T(v, w) using tensordot: 0

Additional example:
V' (column vector): [ 1 -1]
V*' (row vector): [2 1]
Result of T(v', w') using @: -2
Result of T(v', w') using tensordot: -2


申し訳ありません。確かに行列表記が見にくかったですね。LaTeX表記を使って、より明確に表現します。

2次元の例を再度示します：

1. ベクトル空間 V からのベクトル v:

   $$v = \begin{pmatrix} 2 \\ 3 \end{pmatrix}$$

2. 双対空間 V* からのベクトル w:

   $$w = \begin{pmatrix} 1 & -1 \end{pmatrix}$$

3. テンソル T (2×2 行列):

   $$T = \begin{pmatrix} 
   2 & 1 \\
   -1 & 3
   \end{pmatrix}$$

4. 計算:

   $$T(v, w) = w^T T v$$

   $$= \begin{pmatrix} 1 & -1 \end{pmatrix} 
   \begin{pmatrix} 
   2 & 1 \\
   -1 & 3
   \end{pmatrix}
   \begin{pmatrix} 2 \\ 3 \end{pmatrix}$$

   $$= \begin{pmatrix} 1 & -1 \end{pmatrix} 
   \begin{pmatrix} 
   2(2) + 1(3) \\
   -1(2) + 3(3)
   \end{pmatrix}$$

   $$= \begin{pmatrix} 1 & -1 \end{pmatrix} 
   \begin{pmatrix} 7 \\ 7 \end{pmatrix}$$

   $$= 1(7) + (-1)(7) = 0$$

この LaTeX 表記で行列とベクトルの構造がより明確になったと思います。この表現方法は数学的な構造をより正確に伝えることができます。

さらに質問があれば、お気軽にお聞きください。

鋭い観察です！おっしゃる通り、この例では普通の行列計算と区別がつきにくいですね。tensorドット積（tensordot）の視点から見ると、確かにより tensor らしい特徴が見えてきます。

tensordot 操作を使って説明し直しましょう：

1. まず、3次元の例を考えてみます（より tensor の特徴が出やすいため）：

   $$T_{ijk}, \quad v_j, \quad w_k$$

   ここで、$T_{ijk}$ は3階のtensor、$v_j$ はベクトル、$w_k$ は共ベクトルです。

2. tensordot 操作を使うと：

   $$\text{result} = T_{ijk} v_j w_k$$

   これは、$j$ と $k$ について縮約（summation）していることを示しています。

3. 具体的な計算例：

   $$T_{ijk} = \begin{cases}
   1 & \text{if } i+j+k \text{ is even} \\
   0 & \text{otherwise}
   \end{cases}$$

   $$v = \begin{pmatrix} 1 \\ 2 \\ 3 \end{pmatrix}, \quad
   w = \begin{pmatrix} 1 & 1 & 1 \end{pmatrix}$$

4. tensordot 計算：

   $$\text{result}_i = \sum_{j,k} T_{ijk} v_j w_k$$

   これにより、新しいベクトルが生成されます。

5. 2次元の例に戻ると：

   $$T_{ij}, \quad v_j, \quad w_i$$

   $$\text{result} = \sum_{i,j} T_{ij} v_j w_i$$

この表現方法では、tensor の多次元的な性質とインデックスの縮約がより明確になります。通常の行列計算とは異なり、任意の次元で操作を定義でき、どのインデックスについて縮約するかを柔軟に選べます。

この説明で tensor の特徴がより明確になりましたか？この視点から見ると、tensor が単なる行列の拡張ではなく、より一般的で柔軟な数学的対象であることがわかります。

In [20]:
import numpy as np

# 3階のtensorを定義


def create_tensor():
    T = np.zeros((3, 3, 3))
    for i in range(3):
        for j in range(3):
            for k in range(3):
                T[i, j, k] = 1 if (i + j + k) % 2 == 0 else 0
    return T


# ベクトルとテンソルの定義
T = create_tensor()
v = np.array([1, 2, 3])
w = np.array([1, 1, 1])

print("Tensor T:")
print(T)

print("\nVector v:", v)
print("Vector w:", w)

# tensordotを使用した計算
result = np.tensordot(np.tensordot(T, v, axes=([1], [0])), w, axes=([1], [0]))

print("\nResult using tensordot:", result)

# 比較: 直接的なループ計算
result_loop = np.zeros(3)
for i in range(3):
    for j in range(3):
        for k in range(3):
            result_loop[i] += T[i, j, k] * v[j] * w[k]

print("Result using loop:", result_loop)

# 結果が一致することを確認
print("\nResults match:", np.allclose(result, result_loop))

Tensor T:
[[[1. 0. 1.]
  [0. 1. 0.]
  [1. 0. 1.]]

 [[0. 1. 0.]
  [1. 0. 1.]
  [0. 1. 0.]]

 [[1. 0. 1.]
  [0. 1. 0.]
  [1. 0. 1.]]]

Vector v: [1 2 3]
Vector w: [1 1 1]

Result using tensordot: [10.  8. 10.]
Result using loop: [10.  8. 10.]

Results match: True


In [21]:
import numpy as np

# rank-4 テンソル T の定義 (4x4x4x4)
T = np.random.rand(4, 4, 4, 4)

# ベクトル v と w の定義 (各4次元)
v = np.array([1, 2, 3, 4])
w = np.array([0.1, 0.2, 0.3, 0.4])

# rank-2 テンソル R の計算
R = np.einsum('ijkl,i,j->kl', T, v, w)

print("Shape of R:", R.shape)
print("R:\n", R)

Shape of R: (4, 4)
R:
 [[5.56997713 4.15262191 4.95653662 5.74060382]
 [4.58603573 5.327253   6.66091597 4.43335805]
 [4.66049317 4.58301202 4.5975141  4.4469637 ]
 [5.77731443 5.52972173 5.45984673 4.75749654]]


もちろんです。3次元の例を使って、一歩一歩丁寧に説明します。V, V*, そしてTを用いた計算の過程を詳細に示し、Pythonでの検算も行います。

まず、設定から始めましょう：

1. 設定:
   - V: 3次元ベクトル空間
   - V*: V の双対空間
   - T: 3次元のrank-2テンソル（3×3行列）

2. 具体的な値:

   v ∈ V (列ベクトル):
   $$v = \begin{pmatrix} 1 \\ 2 \\ 3 \end{pmatrix}$$

   w ∈ V* (行ベクトル):
   $$w = \begin{pmatrix} 4 & 5 & 6 \end{pmatrix}$$

   T (3×3 行列):
   $$T = \begin{pmatrix} 
   1 & 2 & 3 \\
   4 & 5 & 6 \\
   7 & 8 & 9
   \end{pmatrix}$$

3. 計算過程:
   目標: T(v, w) = wᵀTv を計算する

   ステップ 1: Tv を計算
   $$Tv = \begin{pmatrix} 
   1 & 2 & 3 \\
   4 & 5 & 6 \\
   7 & 8 & 9
   \end{pmatrix} \begin{pmatrix} 1 \\ 2 \\ 3 \end{pmatrix}$$

   $$= \begin{pmatrix} 
   1(1) + 2(2) + 3(3) \\
   4(1) + 5(2) + 6(3) \\
   7(1) + 8(2) + 9(3)
   \end{pmatrix}$$

   $$= \begin{pmatrix} 14 \\ 32 \\ 50 \end{pmatrix}$$

   ステップ 2: w(Tv) を計算
   $$w(Tv) = \begin{pmatrix} 4 & 5 & 6 \end{pmatrix} \begin{pmatrix} 14 \\ 32 \\ 50 \end{pmatrix}$$

   $$= 4(14) + 5(32) + 6(50)$$
   
   $$= 56 + 160 + 300 = 516$$

したがって、T(v, w) = 516 です。


In [22]:

import numpy as np

# ベクトルとテンソルの定義
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])
T = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# 手順1: Tv の計算
Tv = np.dot(T, v)
print("Tv =", Tv)

# 手順2: w(Tv) の計算
result = np.dot(w, Tv)
print("T(v, w) =", result)

# numpy の tensordot を使用した一括計算
result_tensordot = np.tensordot(np.tensordot(T, v, axes=1), w, axes=1)
print("T(v, w) using tensordot =", result_tensordot)

# 結果が一致することを確認
print("Results match:", result == result_tensordot)

Tv = [14 32 50]
T(v, w) = 516
T(v, w) using tensordot = 516
Results match: True


In [24]:
import numpy as np

# 3次元テンソル T (2x2x2)
T = np.array([[[1, 2],
               [3, 4]],
              [[5, 6],
               [7, 8]]])

# ベクトル v (長さ2)
v = np.array([1, 2])

# ベクトル w (長さ2)
w = np.array([3, 4])

# NumPyのtensordotを使用した一括計算
result_tensordot = np.tensordot(np.tensordot(T, v, axes=1), w, axes=1)
print("\nT(v, w) using tensordot:")
print(result_tensordot)


T(v, w) using tensordot:
[ 59 143]
